### ISSUE TITLE
Running out of disk space

### ISSUE THREAD

**Issue by keenangraham** [LUMC/pytest-workflow#96] opened 2020-04-10 22:19 UTC
Thanks for the great library. We've been making heavy use of it on one of the WDL pipelines we're developing: https://github.com/ENCODE-DCC/dnase-seq-pipeline

In general we split our tests up into unit, integration, and functional tests, and run each of these groups separately on circleCI. Most of our WDL tasks are thin wrappers over command-line utilities, and we use our unit tests specifically to ensure our tasks are emitting the correct command given some input. (We use our integration/functional tests to actually compare outputs.)

We've recently run into a problem that we've added so many unit tests (https://github.com/ENCODE-DCC/dnase-seq-pipeline/tree/dev/tests/unit) that our circleCI machine is running out of disk space (~100GB). It appears every stdout contains assertion is counted as a separate test and our repo (around 1.2GB because of some test data stored in git-lfs) gets copied to a temp directory over and over: https://github.com/LUMC/pytest-workflow/blob/db438b6b8fb0e64779084a29d9e8642385d8ba73/src/pytest_workflow/plugin.py#L344

While this makes sense for how pytest-workflow is supposed to work I'm wondering if there's a way to reduce the disk space footprint, either by using some kind of symlinking or by collecting and running tests in batches instead of all upfront?

This isn't too urgent. Our current workaround is just to add a second unit test tag and split our tests across two circleCI machines. In general though it would be nice to have a scalable solution and only maintain one `--tag unit` instead of multiple arbitrary groups like `--tag unit1`, `--tag unit2` etc.

**Comment by rhpvorderman** [comment] 2020-04-14 06:42
Thanks for submitting an issue! It is nice to know that this project is used outside of the LUMC as well.

> While this makes sense for how pytest-workflow is supposed to work I'm wondering if there's a way to reduce the disk space footprint, either by using some kind of symlinking or by collecting and running tests in batches instead of all upfront?

Collecting and running tests in batches is not an option I am affraid. This is not how pytest works. All tests are collected at once. I could move the copy step to the workflow run step however, but that will require more complex code and will not solve the problem. Also, I can not run the workflows in the test phase, because then I can not share the same workflow across multiple tests, and that would be extremely wasteful.

As regards to symlinking and hardlinking. This is very risky. This means that your workflow tests can alter the files in your repo. This can lead to all sorts of race conditions between tests. This can only work if the tests open files read-only (which they do mostly). But care has to be taken that tests do not share the same `cromwell-executions` directory for example.

> We've recently run into a problem that we've added so many unit tests (https://github.com/ENCODE-DCC/dnase-seq-pipeline/tree/dev/tests/unit) that our circleCI machine is running out of disk space (~100GB). It appears every stdout contains assertion is counted as a separate test and our repo (around 1.2GB because of some test data stored in git-lfs) gets copied to a temp directory over and over:

pytest-workflow's explicit purpose has always been the running of workflows. While I am open to adding your use case I am thinking it will be a terrible tool for the job. For testing a simple task it will:

1. Copy the git repo. Or will use some function to create links (which has to be added).
2. Will start a subprocess in that folder.
3. Said subprocess will be a shellscript that starts cromwell.
4. Cromwell is a server and will take 40 seconds at least to initialize. It will accept the workflow and run it.
5. Pytest-workflow will wait for the subprocess to finish.
6. Pytest-workflow starts the tests, that check for a few strings.

This is quite a lot of work for one task. Not to mention all the work you have to do with creating a workflow and a test file.

Do you know about [miniwdl](https://github.com/chanzuckerberg/miniwdl)? It can run WDL tasks without requiring a workflow. 
You could use pytest directly: create some function that runs miniwdl for you, and then collects the output of the task. You could even do so without calling subprocess but instead using the python functions from the [miniwdl runtime](https://github.com/chanzuckerberg/miniwdl/tree/master/WDL/runtime). That would be much more lightweight for your unit tests. Would that alleviate your problems?

**Comment by Redmar-van-den-Berg** [comment] 2020-04-14 08:18
Could a solution for issue #78 help here?

**Comment by keenangraham** [comment] 2020-04-14 17:24
@rhpvorderman Thanks for your thoughts on this. I agree you could probably do something interesting with miniwdl. We use [caper](https://github.com/ENCODE-DCC/caper) as our WDL runner/Cromwell wrapper in production, and it's nice to have a consistent use of this across all of our tests.

> This is quite a lot of work for one task.

While there is a bit of overhead here we've found even simple string checking to be extremely helpful for  development and maintainability. 

> Not to mention all the work you have to do with creating a workflow and a test file.

Agree. But it does ensure the task can be called by a workflow (as it will be in production), and it leaves a record of how a specific task should be called.

> Could a solution for issue #78 help here?

This seems along the right lines but I agree it would be tricky for our special use case. Our unit tests don't necessarily need access to our git-lfs data but our integration/functional tests do.

In any case thanks again for this library. It's much less painful than our previous methods of testing and it's nice to have the familiar pytest underneath.

**Comment by rhpvorderman** [comment] 2020-04-15 06:26
> We use caper as our WDL runner/Cromwell wrapper in production, and it's nice to have a consistent use of this across all of our tests.

I completely understand. We also use pytest-workflow in production that way. You are always sure a certain command "just works" which is extremely useful and powerful.

> In any case thanks again for this library. It's much less painful than our previous methods of testing and it's nice to have the familiar pytest underneath.

Thanks for letting us know! I feel a bit sad that I was not able to provide a more helpful response :disappointed: . I think a recursive soft-linking strategy could work wonders in your particular use case. It should not be too hard to implement. It will not be the default mode of operation, but it could be nice as a feature turned on by a flag.

**Comment by rhpvorderman** [comment] 2020-04-15 15:31
@keenangraham Hi! I have created a new symlink strategy. Could you test this branch with your CI and see if it works as intended? I have made tests and it should work, but still it is good to do a production level test.
You can install the branch with `pip install  git+https://github.com/LUMC/pytest-workflow.git@linkcopy`.

Does this solve the problems you have on the CI?

**Comment by keenangraham** [comment] 2020-04-15 18:28
Excellent! This appears to be working great: https://github.com/ENCODE-DCC/dnase-seq-pipeline/compare/symlink-pytest-workflow

Disk usage on circle is no longer ballooning and test collection is a lot faster (cuts running time in half in one case).

Thanks so much for your work on this.

**Comment by rhpvorderman** [comment] 2020-04-16 06:41
Thanks for testing this! The linkcopy branch will be merged soon and be deleted. If you want continued functioning of the CI, the installed should be pinned at the commit instead: `pip install  git+https://github.com/LUMC/pytest-workflow.git@cd8c7d6e`. Alternatively you can pin it at develop after the merge.

There should be a 1.3.0 release coming soon with this feature in it. You can watch "releases only" on github, so you'll be notified.

**Closed** 2020-04-16 07:12 UTC
